name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Create New Release Version
        uses: TriPSs/conventional-changelog-action@v6
        id: changelog
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          skip-version-file: 'true'
          skip-commit: 'true'
          tag-prefix: ''
          release-count: 0
          output-file: 'CHANGELOG.md'
          fallback-version: '1.0.0'
          git-push: false
      
      - name: Update Version in Docs
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          echo "Configuring git locally..."
          git config --local user.name "${{ secrets.USERNAME }}"
          git config --local user.email "${{ secrets.EMAIL }}"
          
          echo "Updating README file..."
          sed -E -i "s/(from: \"([0-9]+\.[0-9]+\.[0-9])\")/from: \"${{ steps.changelog.outputs.tag }}\"/g" README.md
          git add README.md
          
          echo "Adding CHANGELOG file..."
          git add CHANGELOG.md
          
          echo "Committing changes..."
          git commit -m "release: ${{ steps.changelog.outputs.tag }} [skip ci]"
          
          echo "Pushing changes to remote..."
          git push origin
          
          echo "Creating tag [${{ steps.changelog.outputs.tag }}]..."
          git tag -d "${{ steps.changelog.outputs.tag }}"
          git tag "${{ steps.changelog.outputs.tag }}"
          
          echo "Pushing tag to remote..."
          git push origin ${{ steps.changelog.outputs.tag }}
      
      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.ACCESS_TOKEN }}
