name: Semantic Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      
permissions:
  pull-requests: write
      
jobs:
  validate-pull-request:
    name: Validate Pull Request title
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          wip: true
          types: |
            feat
            fix
            build
            ci
            docs
            refactor
            perf
            test
            chore
            release
          requireScope: false
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
